## Cursos MAI5024/SCC5848 - INTRODUÇÃO A CIENCIA DE DADOS
## Profa. Roseli Ap. Francelin Romero
## **Exercício 03 - Entrega 05 de abril de 2024**
## Transformação nos dados e Seleção de variáveis
### Alunos:

- Julyana Flores de Prá (NUSP: 15600911)
- Thiago Rafael Mariotti Claudio (NUSP: 15611674)

---

Nesse exercício utilizaremos um dataset para classificação binária. No total são 19 variáveis de entrada e 1 variável de saída. O dataset pode ser encontrado no arquivo "dataset_hepatitis.csv".

Existem valores faltantes nesse dataset, representados pelo caractere "?".

**Há material complementar disponível para resolução desse exercício. Acesse o arquivo "Transformações em dados heterogeneos" antes de prosseguir.**

### Questão 01.

Carregue o dataset (`pandas.read_csv`) e interprete os valores ausentes corretamente. Utilize o parâmetro `na_values`.

---

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("./hepatitis.csv", na_values = "?")
display(df)

,AGE,SEX,STEROID,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER_BIG,LIVER_FIRM,SPLEEN_PALPABLE,SPIDERS,ASCITES,VARICES,BILIRUBIN,ALK_PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY,Class
0,30,male,no,no,no,no,no,no,no,no,no,no,no,1.0,85.0,18.0,4.0,NaN,no,1
1,50,female,no,no,yes,no,no,no,no,no,no,no,no,0.9,135.0,42.0,3.5,NaN,no,1
2,78,female,yes,no,yes,no,no,yes,no,no,no,no,no,0.7,96.0,32.0,4.0,NaN,no,1
3,31,female,NaN,yes,no,no,no,yes,no,no,no,no,no,0.7,46.0,52.0,4.0,80.0,no,1
4,34,female,yes,no,no,no,no,yes,no,no,no,no,no,1.0,NaN,200.0,4.0,NaN,no,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,46,female,yes,no,yes,yes,yes,yes,no,no,yes,yes,yes,7.6,NaN,242.0,3.3,50.0,yes,0
151,44,female,yes,no,yes,no,no,yes,yes,no,no,no,no,0.9,126.0,142.0,4.3,NaN,yes,1
152,61,female,no,no,yes,yes,no,no,yes,no,yes,no,no,0.8,75.0,20.0,4.1,NaN,yes,1
153,53,male,no,no,yes,no,no,yes,no,yes,yes,no,yes,1.5,81.0,19.0,4.1,48.0,yes,1
154,43,female,yes,no,yes,no,no,yes,no,yes,yes,yes,no,1.2,100.0,19.0,3.1,42.0,yes,0

Vamos verificar o tipo dos dados nesse dataset, além da contagem de valores desconhecidos.

In [2]:
display(df.dtypes)

AGE                  int64
SEX                 object
STEROID             object
ANTIVIRALS          object
FATIGUE             object
MALAISE             object
ANOREXIA            object
LIVER_BIG           object
LIVER_FIRM          object
SPLEEN_PALPABLE     object
SPIDERS             object
ASCITES             object
VARICES             object
BILIRUBIN          float64
ALK_PHOSPHATE      float64
SGOT               float64
ALBUMIN            float64
PROTIME            float64
HISTOLOGY           object
Class                int64
dtype: object

In [3]:
display(df.isna().sum())

AGE                 0
SEX                 0
STEROID             1
ANTIVIRALS          0
FATIGUE             1
MALAISE             1
ANOREXIA            1
LIVER_BIG          10
LIVER_FIRM         11
SPLEEN_PALPABLE     5
SPIDERS             5
ASCITES             5
VARICES             5
BILIRUBIN           6
ALK_PHOSPHATE      29
SGOT                4
ALBUMIN            16
PROTIME            67
HISTOLOGY           0
Class               0
dtype: int64

Podemos verificar também a ocorrência de valores desconhecidos por coluna.



---

### Questão 02.

Nessa questão, você irá fazer o pré-processamento dos dados.

Você deve:


*   **Para os dados numéricos:** substitua os valores faltantes utilizando a estratégia de média (`sklearn.impute.SimpleImputer`). Depois padronize o intervalo dessas variáveis (`sklearn.preprocessing.StandardScaler`)
*   **Para os dados categóricos:** substitua os valores faltantes utilizando a estratégia de mais frequentes (`sklearn.impute.SimpleImputer`). Depois converta os dados categóricos para uma representação numérica (`sklearn.preprocessing.OneHotEncoder`),

Lembre-se de utilizar as classes `sklearn.pipeline.Pipeline` e `sklearn.compose.ColumnTransformer` conforme consta no material complementar.

---
Primeiramente vamos separar os dados do tipo categórico e númerico em dois conjuntos.  
Observando o dataset podemos confirmar que existem colunas númericas, __Idade__, __Bilirrubina__,__Quinase de Linfoma Anaplasico__, __Transaminase glutâmico-oxalacética__, __Albumina__ e __Trombina__.

In [4]:
col_numerico = ['AGE','BILIRUBIN','ALK_PHOSPHATE','SGOT','ALBUMIN','PROTIME']
col_categorico = list(df.columns[~df.columns.isin(col_numerico)]) # prova de que qualquer coisa funciona em Python
col_categorico.pop(-1)
print(f"Numericos: {col_numerico}")
print(f"Categoricos: {col_categorico}")

Numericos: ['AGE', 'BILIRUBIN', 'ALK_PHOSPHATE', 'SGOT', 'ALBUMIN', 'PROTIME']
Categoricos: ['SEX', 'STEROID', 'ANTIVIRALS', 'FATIGUE', 'MALAISE', 'ANOREXIA', 'LIVER_BIG', 'LIVER_FIRM', 'SPLEEN_PALPABLE', 'SPIDERS', 'ASCITES', 'VARICES', 'HISTOLOGY']

Agora que os dados estão devidamente tratados, podemos realizar as operações de imputação.

In [5]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

pipeline_numerico = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())])

pipeline_categorico = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder())])

transformacao = ColumnTransformer(
    transformers=[
        ('transformacao numerica', pipeline_numerico, col_numerico),
        ('transformacao categorica', pipeline_categorico, col_categorico),
    ])

# Aplicando a transformação no dataset:
dados_imputados = transformacao.fit_transform(df)
dados_imputados.round(2)

array([[-0.89, -0.36, -0.44, ...,  0.  ,  1.  ,  0.  ],
       [ 0.7 , -0.45,  0.64, ...,  0.  ,  1.  ,  0.  ],
       [ 2.94, -0.61, -0.2 , ...,  0.  ,  1.  ,  0.  ],
       ...,
       [ 1.58, -0.53, -0.66, ...,  0.  ,  0.  ,  1.  ],
       [ 0.94,  0.06, -0.53, ...,  1.  ,  0.  ,  1.  ],
       [ 0.14, -0.19, -0.12, ...,  0.  ,  0.  ,  1.  ]])

In [6]:
df_imp = np.c_[dados_imputados, df['Class']]
df2 = pd.DataFrame(df_imp)
display(df2)

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,-0.894192,-0.360938,-4.394144e-01,-0.769834,0.297246,-4.146013e-16,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
1,0.702579,-0.445364,6.415347e-01,-0.497704,-0.516084,-4.146013e-16,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
2,2.938059,-0.614217,-2.016056e-01,-0.611092,0.297246,-4.146013e-16,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
3,-0.814353,-0.614217,-1.282555e+00,-0.384316,0.297246,1.058919e+00,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
4,-0.574838,-0.360938,-3.072242e-16,1.293820,0.297246,-4.146013e-16,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,0.383225,5.211214,-3.072242e-16,1.770048,-0.841416,-6.915795e-01,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
151,0.223548,-0.445364,4.469639e-01,0.636172,0.785243,-4.146013e-16,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0
152,1.580803,-0.529791,-6.556042e-01,-0.747157,0.459911,-4.146013e-16,1.0,0.0,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0
153,0.942095,0.061195,-5.258903e-01,-0.758496,0.459911,-8.082794e-01,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0
154,0.143709,-0.192085,-1.151297e-01,-0.758496,-1.166747,-1.158379e+00,1.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0

In [7]:
labels = []
labels = labels + col_numerico

transformacao_categorica = transformacao.transformers_[1]
pipeline_categorico = transformacao_categorica[1]
transf_onehot = pipeline_categorico.named_steps['onehot']

In [8]:
print(transf_onehot.get_feature_names_out())

['x0_female' 'x0_male' 'x1_no' 'x1_yes' 'x2_no' 'x2_yes' 'x3_no' 'x3_yes'
 'x4_no' 'x4_yes' 'x5_no' 'x5_yes' 'x6_no' 'x6_yes' 'x7_no' 'x7_yes'
 'x8_no' 'x8_yes' 'x9_no' 'x9_yes' 'x10_no' 'x10_yes' 'x11_no' 'x11_yes'
 'x12_no' 'x12_yes']

In [9]:
get_labels_categoricas = [col_categorico[int(x.split("_")[0].split("x")[1])] + "_" + x.split("_")[1] for x in transf_onehot.get_feature_names_out().tolist()]

labels = labels + get_labels_categoricas
labels.append("Class")

df2 = pd.DataFrame(df_imp, columns= labels)
df2

,AGE,BILIRUBIN,ALK_PHOSPHATE,SGOT,ALBUMIN,PROTIME,SEX_female,SEX_male,STEROID_no,STEROID_yes,...,SPLEEN_PALPABLE_yes,SPIDERS_no,SPIDERS_yes,ASCITES_no,ASCITES_yes,VARICES_no,VARICES_yes,HISTOLOGY_no,HISTOLOGY_yes,Class
0,-0.894192,-0.360938,-4.394144e-01,-0.769834,0.297246,-4.146013e-16,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
1,0.702579,-0.445364,6.415347e-01,-0.497704,-0.516084,-4.146013e-16,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
2,2.938059,-0.614217,-2.016056e-01,-0.611092,0.297246,-4.146013e-16,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
3,-0.814353,-0.614217,-1.282555e+00,-0.384316,0.297246,1.058919e+00,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
4,-0.574838,-0.360938,-3.072242e-16,1.293820,0.297246,-4.146013e-16,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,0.383225,5.211214,-3.072242e-16,1.770048,-0.841416,-6.915795e-01,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
151,0.223548,-0.445364,4.469639e-01,0.636172,0.785243,-4.146013e-16,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0
152,1.580803,-0.529791,-6.556042e-01,-0.747157,0.459911,-4.146013e-16,1.0,0.0,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0
153,0.942095,0.061195,-5.258903e-01,-0.758496,0.459911,-8.082794e-01,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0
154,0.143709,-0.192085,-1.151297e-01,-0.758496,-1.166747,-1.158379e+00,1.0,0.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0



---

### Questão 03.

Determine as 10 variáveis mais relevantes do conjunto (lembre-se de concatenar a variável alvo no dataset transformado, isto é, após transformar os dados). Você pode utilizar a matriz de covariância (`numpy.cov`), correlação (`pandas.DataFrame.corr`), `scatterplot`, etc. Justifique sua escolha.

Lembre-se que heatmaps (`seaborn.heatmap`) podem auxiliar a visualização.

---
Queremos encontrar as variáveis com maior correlação à classe-alvo __Class__ (indicativo binário de Hepatite).  
Podemos usar a função __.corr()__ do _Pandas_ para gerar uma lista ordenada das _features_ mais relevantes.  

__Obs.:__ Devido a natureza simétrica dos dados categoricos (sim e não) podemos remover todas as colunas categóricas que terminam com __\_no__, uma vez que seu binário é exatamente o oposto do valor da mesma _feature_ terminada com __\_yes__ (por exemplo, __FATIGUE_no__ = 0 indica __FATIGUE_YES__ = 1).

In [10]:
colunas_para_remover = [col for col in df2.columns if col.endswith('_no')]
df2.drop(columns=colunas_para_remover + ['SEX_male'], inplace=True)

corr_list = df2.corr()['Class'].sort_values(ascending=False, key=abs)

print(corr_list.head(11))

Class                  1.000000
ASCITES_yes           -0.469334
ALBUMIN                0.465827
BILIRUBIN             -0.450470
SPIDERS_yes           -0.389137
VARICES_yes           -0.362385
MALAISE_yes           -0.339530
HISTOLOGY_yes         -0.337856
PROTIME                0.307238
FATIGUE_yes           -0.306049
SPLEEN_PALPABLE_yes   -0.234261
Name: Class, dtype: float64

Verifica-se que as _features_ com maior correlação a Classe alvo são:
1. Ascite
2. Albumina
3. Bilirubin
4. Angioma Estelar (Spiders)
5. Varizes
6. Mal-estar (malaise)
7. Hystology
8. Tombina (Protime)
9. Fadiga
10. Baço (Spleen Palpable)



---

### Questão 04.

Com as 10 varíaveis determinadas na questão anterior, crie um novo conjunto de dados.

Lembre-se que o numpy permite indexar colunas/linhas utilizando arrays.

In [11]:
df_corr = df2[corr_list.head(11).index.tolist()] # mais uma prova de que qualquer coisa funciona em Python

In [12]:
display(df_corr)

,Class,ASCITES_yes,ALBUMIN,BILIRUBIN,SPIDERS_yes,VARICES_yes,MALAISE_yes,HISTOLOGY_yes,PROTIME,FATIGUE_yes,SPLEEN_PALPABLE_yes
0,1.0,0.0,0.297246,-0.360938,0.0,0.0,0.0,0.0,-4.146013e-16,0.0,0.0
1,1.0,0.0,-0.516084,-0.445364,0.0,0.0,0.0,0.0,-4.146013e-16,1.0,0.0
2,1.0,0.0,0.297246,-0.614217,0.0,0.0,0.0,0.0,-4.146013e-16,1.0,0.0
3,1.0,0.0,0.297246,-0.614217,0.0,0.0,0.0,0.0,1.058919e+00,0.0,0.0
4,1.0,0.0,0.297246,-0.360938,0.0,0.0,0.0,0.0,-4.146013e-16,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
150,0.0,1.0,-0.841416,5.211214,1.0,1.0,1.0,1.0,-6.915795e-01,1.0,0.0
151,1.0,0.0,0.785243,-0.445364,0.0,0.0,0.0,1.0,-4.146013e-16,1.0,0.0
152,1.0,0.0,0.459911,-0.529791,1.0,0.0,1.0,1.0,-4.146013e-16,1.0,0.0
153,1.0,0.0,0.459911,0.061195,1.0,1.0,0.0,1.0,-8.082794e-01,1.0,1.0
154,0.0,1.0,-1.166747,-0.192085,1.0,0.0,0.0,1.0,-1.158379e+00,1.0,1.0



---

### Questão 05.

Reduza a dimensionalidade do conjunto de dados criado utilizando a técnica PCA (`sklearn.decomposition.PCA`). Reduza a dimensionalidade de forma que no mínimo 80% da variância dos dados seja mantida (atente-se ao atributo  `explained_variance_ratio_`). Depois exiba os eixos principais.

In [19]:
from sklearn.decomposition import PCA

for qtd_componentes in range(11,1,-1):
    pca = PCA(n_components=qtd_componentes)
    pca.fit(df_corr)
    df_pca = pca.fit_transform(df_corr)
    print(f"A variancia para {qtd_componentes} é de {sum(pca.explained_variance_ratio_)}")

A variancia para 11 é de 0.9999999999999999
A variancia para 10 é de 0.9867352723545401
A variancia para 9 é de 0.9709728863785847
A variancia para 8 é de 0.9525378750527548
A variancia para 7 é de 0.9297621931088466
A variancia para 6 é de 0.9022465504724264
A variancia para 5 é de 0.8667105861670197
A variancia para 4 é de 0.8092601575767866
A variancia para 3 é de 0.7370831851733991
A variancia para 2 é de 0.5983808501238521

In [20]:
pca = PCA(n_components=4)
pca.fit(df_corr)
df_pca = pca.fit_transform(df_corr)
pd.DataFrame(df_pca)

            0         1         2         3
0   -0.740612  0.290331  0.050115 -0.699204
1   -0.158335  0.203283 -0.626387 -0.339545
2   -0.715272  0.394968 -0.129839 -0.084259
3   -1.361964 -0.456699 -0.396212 -0.527106
4   -0.740612  0.290331  0.050115 -0.699204
..        ...       ...       ...       ...
150  4.266199 -2.413076  2.630268 -0.318840
151 -0.744382  0.364906  0.303666  0.176020
152 -0.283916  0.310845 -0.004950  1.096723
153  0.439699  0.646864  0.585890  0.444704
154  1.612760  0.855998 -0.795019  0.176768

[155 rows x 4 columns]

---

A menor quantidade de componentes possíveis mantendo a variância dos dados acima de 80% é __4__.